version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "**/*"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    labels:
      - "cargo"
      - "dependencies"
    groups:
      cargo-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "🧹 chore"
      include: "scope"

  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    labels:
      - "rust"
      - "dependencies"
    groups:
      rust-toolchain:
        patterns:
          - "*"
    commit-message:
      prefix: "🧹 chore"
      include: "scope"
